### ISSUE TITLE
Cannot use the configJSON property

### ISSUE THREAD

**Issue by FredAlainCodjia** [shivuparagi/GenericLookupPCFControl#2]
Hello,
Your PCF is great, but i cannot put my configJSON in the property of the PCF. Actually, the property field only allow 100 characters whereas the field should be a multiple line of text.
Can you fix the issue (allow up to 5000 characters in the field) so I can use it ?

Thank you
<img width="305" alt="Config JSON issue" src="https://user-images.githubusercontent.com/78079220/108193356-a451ac80-7115-11eb-99ba-2049f9f8cb09.png">

**Comment by shivuparagi** [comment]
Hi,

Thank you for your email.

Please go developer tools (F12) ==> Inspect the TEXTBOX ==> Increase the
max length of the textaree as shown in the attached screenshot.

Thanks and regards,
Shivakumar Paragi

**Comment by FredAlainCodjia** [comment]
Just tried it, it works perfect !
Thank you for your swift answer.

Regards,

Fred-Alain Codjia

**Comment by shivuparagi** [comment]
Thank you so much.

Thanks and Regards,
Shivakumar Paragi
