### ISSUE TITLE
Control not available during record creation (before first save)

### ISSUE THREAD

**Issue by FredAlainCodjia** [shivuparagi/GenericLookupPCFControl#3]
Hello,

Your control works very well but I noticed that it is not available on record creation. Actually, I must save for the first time my record before have access to the control.
Is it possible to have a version that will work during record creation ?
Thank you so much in advance.

Regards,

Fred-Alain Codjia
<img width="284" alt="Control not available" src="https://user-images.githubusercontent.com/78079220/108376764-9c703600-7203-11eb-8a2b-6345d56ea2cb.png">
<img width="260" alt="after saving" src="https://user-images.githubusercontent.com/78079220/108376765-9d08cc80-7203-11eb-8b83-99d5d85a21b6.png">

**Comment by shivuparagi** [comment]
Hi,

I will check this and will get back to you as soon as possible.

Thanks and regards,
Shivakumar Paragi

**Comment by FredAlainCodjia** [comment]
Hello,

Do you have any feedback regarding my issue ?
Thank you for your answer.

Regards,

Fred-Alain Codjia

**Comment by shivuparagi** [comment]
Hi,

I am working on this and will get back to you soon.

Thanks and regards,
Shivakumar Paragi

**Comment by vernetmatias** [comment]
Hello, I like you control it's usefull, but sadly I couldn't make it work. It does not render. Here is the  ConfigJSON Im uploading:
I, m tryng to put it in opportunity entity, to replace parentaccount look up.

{
  "name": "parentaccountid", // Name of the actual lookup field
  "openSearchPanelOnKeyDown": true, // true: search will be done as and when user types. false: search will be done when user clicks search icon.
  "recordsThreshHoldLimit": 5000, // Number of records to be fetched upon search
  "newRecordText": "Create New Account", // Text to be shown for Create Record
  "focusControl": "focusControl1", // Focus control (in case of more number of Lookup fields on same form, do increament the number)
  "entitySymbol": "Account", // Symbol of the entity
  "lookUpCol": {
    "entity": "account", // Name of the actual lookup field
    "schemaName": "ParentAccountId", // Schema name of the actual lookup field
    "pageUrl": "", // Relative URL of the lookup field entity form
    "primaryKey": "accountid", // Primary Key of the looked up entity
    "primaryFeild": "name", // Primay Key Name       //<----my comment: Is this "feild" correctly typed? "primaryFeild", or should be "primaryField"?
    // Fields by which filter needs be performed (OR condition)
    "fitlerTextFields": [
      {
        "name": "name",
        "displayText": "Currency Name"
      }
    ],
    // Fields to show in results set
    "fieldsToShow": [
      {
        "name": "name",
        "displayText": "Currency Name"
      }
    ],
    // Views. First one be default. For fetchXML, have the required FETCHXML and add <MORECONDITIONS/> at the end of the filter which will be replaced dynamically
    "views": [
      {
        "id": 0,
        "name": "Todas las personas"
      }
    ]
  }
}

![image](https://user-images.githubusercontent.com/36961292/109323988-d90ae580-7832-11eb-9961-66f988eb04f8.png)

**Comment by shivuparagi** [comment]
Hi,

I tested it today and it is working fine in Quick Create Form. Can you
please check again and let me know?

Thanks and Regards,
Shivakumar Paragi

**Comment by shivuparagi** [comment]
Hi,

Thank you for your email. May I request you to please take a sample config
and modify it accordingly? Also please note that, while pasting the config
in the ConfigJSON field, please make sure to copy the entire text as the
textbox takes a max of 100 characters. I have provided a workaround for it.
Please check it.

Also regarding, making New record optional, I am working on it and will
get back to you soon.

Thanks & Regards,
Shivakumar Paragi

**Comment by vernetmatias** [comment]
Hello, thanks for answering. I aware of the workaround, I did it and make
sure to paste all the code. But I tried several times but I couldn't make
it work. I don't know where I'm failing when I modify your sample code.
I have a few questions:

Whats the reference entitySymbol?

Is the tag name "primaryFeild" correct? Shouldn't it be "primaryField" in
the sample code is typed like that.

When you say "actual lookup" you referring to the lookup that I'm trying to
emulate?

"Page url" it's require? where can I get it?

"fitlerTextFields" is correct? Or shouldn't it be "filterTextFields"?

In the name of the view has to be exactly the name of the view?

The "id" of the view has to be the GUID?

thanks

**Comment by vernetmatias** [comment]
Hello I made it work!, But I have a requirement could I hide the "New"
button?

**Comment by FredAlainCodjia** [comment]
Hello,

@vernetmatias can you create your own issue thread so it will be clearer for anyone who is searching for answers ?
This one was created for enabling the control during a record creation.

@shivuparagi I hope you are doing fine. Please tell me when you have any solution for me :)

Thank you

Regards

Fred-Alain Codjia

**Comment by vernetmatias** [comment]
Ok, I will do that.

**Comment by lakshmipriyanka08** [comment]
Hi shivuparagi ,

Where you able to fix a solution for the above? I am also facing the same issue. Your help would be appreciated.

Regards,
G Lakshmi Priyanka

**Comment by FredAlainCodjia** [comment]
Hello again Shivakumar,

Do you had the time to take a look at this issue ?
Regards,

Fred-Alain

**Comment by shivuparagi** [comment]
Yes, both issues. I will post it soon.

Thank you

**Comment by lakshmipriyanka08** [comment]
Hi ShivaKumar,


Any stipulated time for the release you are planning?
Or could just give me a hint on the fix because I have an deliverable item
which very critical.


Regards,
G Lakshmi Priyanka

**Comment by shivuparagi** [comment]
Hi,

This is fixed now. Please try with the latest solution and associated code change.

Thanks and regards,
Shivakumar

**Comment by FredAlainCodjia** [comment]
Hello Shivakumar,

I tried the new release by downloading the solution available on the link (check the screenshot)
![image](https://user-images.githubusercontent.com/78079220/112001364-31c25b00-8b1f-11eb-9b08-a40fac4cb9ea.png)

There is no chance on my side. Is the managed solution up to date ?

Thank you

Fred-Alain
