### ISSUE TITLE
hide "New record"

### ISSUE THREAD

**Issue by vernetmatias** [shivuparagi/GenericLookupPCFControl#4]
Hello, shivuparagi, it is posible to hide this button, and another posibility i wanted to ask is If its posible to attach a javascript with a property to open modal form when click New Record with the Xrm.Navigation.navigateTo().

**Comment by shivuparagi** [comment]
Hi,

This is fixed now. Please try with the latest solution and associated code change. Please either set property "newRecordText" to empty.

Thanks and regards,
Shivakumar

**Comment by safanmomin92** [comment]
@vernetmatias When I click on 'Select' button in the list against a record nothing happens. Can you please help me out on this: https://github.com/shivuparagi/GenericLookupPCFControl/issues/12.
