### ISSUE TITLE
Required field not working

### ISSUE THREAD

**Issue by vernetmatias** [shivuparagi/GenericLookupPCFControl#5]
Hello Shivuparagi, it seems that it doest worg if the field is required, it doesn't recognize the field is not null:
![image](https://user-images.githubusercontent.com/36961292/109652331-66ee1580-7b3e-11eb-869b-52f5deb87184.png)

**Comment by shivuparagi** [comment]
Hi,

Let me check this. If you do not mind, can you please send me the config details?

Thanks and regards,
Shivakumar Paragi

**Comment by vernetmatias** [comment]
Here it is:
{
  "name": "parentaccountid",
  "openSearchPanelOnKeyDown": false,
  "recordsThreshHoldLimit": 5000,
  "newRecordText": "Nueva Persona",
  "entitySymbol": "Account",
  "focusControl": "focusControl2",
  "lookUpCol": {
    "entity": "account",
    "schemaName": "ParentAccountId",
    "pageUrl": "",
    "primaryKey": "accountid",
    "primaryFeild": "name",

    "fitlerTextFields": [
      {
        "name": "name",
        "displayText": "Name"
      },
      {
        "name": "emailaddress1",
        "displayText": "Correo electronico"
      },
	  {
        "name": "axx_numerodocumento",
        "displayText": "DNI"
      }
    ],
    "fieldsToShow": [
      {
        "name": "name",
        "displayText": "Name"
      },
      {
        "name": "emailaddress1",
        "displayText": "Correo electronico"
      },
      {
        "name": "axx_numerodocumento",
        "displayText": "DNI"
      }
    ],
    "views": [
      {
        "id": 0,
        "name": "Todas las personas"
      },
	  {
        "id": 1,
        "name": "Personas Físicas - Activas"
      }
    ]
  }
}

**Comment by shivuparagi** [comment]
Hi,

Can you please add a validation attribute just at the same level of "name"?

"validation": {
    "type": "Required",
    "message": "Required fields must be filled in."
  },

Thanks and regards,
Shivakumar Paragi

**Comment by vernetmatias** [comment]
OK!, great, now is working! but it doesn't shows the asterisk "*", aldo still is very usefull. thanks!

![image](https://user-images.githubusercontent.com/36961292/109817630-e64c1980-7c10-11eb-976c-a0f5fb94c6da.png)

**Comment by safanmomin92** [comment]
@vernetmatias When I click on 'Select' button in the list against a record nothing happens. Can you please help me out on this: https://github.com/shivuparagi/GenericLookupPCFControl/issues/12.

**Comment by lakshmipriyanka08** [comment]
hi @vernetmatias /@shivakumar,

Can you please share the updated Json where you added the validation attribute. I am facing similar issue.

thanks in advance.

regards,
Lakshmi Priyanka
