### ISSUE TITLE
Impossible to delete a value if the lookup label is too long

### ISSUE THREAD

**Issue by FredAlainCodjia** [shivuparagi/GenericLookupPCFControl#6]
Hello @shivuparagi ,

I begun the user tests with you control, users really love it !
The thing is that they showed me a little issue regarding the value label on the field.
Actually, if the label is too long, the "X" to delete the value is not displayed anymore and so we cannot make a new lookup searching (check out the screenshots).

Is it possible to have a fix for it or maybe to display the "X" before the value label ?

Regards and thanks for the great work

Fred-Alain

<img width="274" alt="long subject" src="https://user-images.githubusercontent.com/78079220/109795142-e222fa80-7c16-11eb-83f6-07dfdab52ad5.png">
<img width="272" alt="short subject" src="https://user-images.githubusercontent.com/78079220/109795145-e2bb9100-7c16-11eb-9c81-d2ee8c2a9936.png">

**Comment by lakshmipriyanka08** [comment]
Hi FredAlainCodjia ,

Was the first thread issue fixed? "Control not enabled for new record creation before first save"

**Comment by FredAlainCodjia** [comment]
Hello,

Can you please delete your message as it is not related to this issue?
The other one is still opened and Shivakumar is very reactive so he will answer on the right thread...

**Comment by shivuparagi** [comment]
Hi,

Thank you for your email. I will get back to you by this weekend.

Thanks and regards,
Shivakumar Paragi

**Comment by FredAlainCodjia** [comment]
Hello Shivakumar,

I hope you are doing good !
Do you have any news regarding this matter ?

Regards,

Fred-Alain

**Comment by shivuparagi** [comment]
Hi,

I have a fix and will release it soon.

Thanks and regards,
Shivakumar Paragi

**Comment by FredAlainCodjia** [comment]
Good news !
Thank you

Regards,
Fred-Alain

**Comment by FredAlainCodjia** [comment]
Hello Shivakumar,

I hope that you are going well.
You told last week that you have resolve both issues that I logged here.
When do you think you will be able to provide us a new version of your PCF ?

Thanks for the great work

Regards,
Fred-Alain

**Comment by shivuparagi** [comment]
Hi,

This is fixed now. Please try with the latest solution and associated code change.

Thanks and regards,
Shivakumar
