### ISSUE TITLE
record by defect on the dummylookup by error

### ISSUE THREAD

**Issue by vernetmatias** [shivuparagi/GenericLookupPCFControl#7]
Hello shivuparagi, I'm having a problem when i putted the control on a quick create form. When I open it, the field is setted with a record by defect that is blank. It only shows the icon of the entity:

![image](https://user-images.githubusercontent.com/36961292/109863527-81101c80-7c40-11eb-8849-f81b74cc42a7.png)

**Comment by shivuparagi** [comment]
Hi,

This is fixed now. Please try with the latest solution and associated code change.

Thanks and regards,
Shivakumar
