### ISSUE TITLE
<MORECONDITIONS/> replacement?

### ISSUE THREAD

**Issue by maverickandgoose83** [shivuparagi/GenericLookupPCFControl#8]
Less of an issue but more of a question as it is unclear how it works.
In the sample JSON config here is a comment as per below.
` // Views. First one be default. For fetchXML, have the required FETCHXML and add <MORECONDITIONS/> at the end of the filter which will be replaced dynamically`

How does the <MORECONDITIONS/> get replaced Dynamically? what replaces it and where does that get configured?
I'm thinking of scenarios where we would want to add a filter to the lookup based on another field or lookup field on the form like we would do with a prefilter or ootb filtering config. Is that was this is intended for and if so, how does it work?

**Comment by shivuparagi** [comment]
Hi,

It is getting replaced as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/47176537/111918999-b83e5480-8aad-11eb-9935-37c5249a6cb6.png)


Thanks and regards,
Shivakumar Paragi
