### ISSUE TITLE
Control not rendering during record creation (before first save)

### ISSUE THREAD

**Issue by lakshmipriyanka08** [shivuparagi/GenericLookupPCFControl#9]
Hi Shivakumar,

Greetings! hope you are doing good.

I tried alot from  my side for fixing the control on create , but couldnt resolve it. Below is the screenshot that describes the exact error I am facing.
![Capture](https://user-images.githubusercontent.com/79896436/111323769-2f2fb380-8690-11eb-8dcc-81046cef8051.JPG)

can you please help me on the issue. 

Regards,
G lakshmi priyanka

**Comment by shivuparagi** [comment]
Hi,

This is fixed now. Please try with the latest solution and associated code change.

Thanks and regards,
Shivakumar
